#Dev Secure Configuration File

linka:
  username: "![EXJxQ2DrXg3Ne1+XyV6Z/A==]"
  password: "![HiysNYHG7zQeoOWZcdfWrg==]"
  
db:
  username: "![C2Wwr/mxrCOQ8bV/2TYaeA==]"
  password: "![6uEbA/e5JCjK4WEiWNznqg==]"